jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用 Ubuntu 环境

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Git 用户信息
      - name: Set git config
        run: |
          git config --global user.email "amliubo@163.com"
          git config --global user.name "LiuBo"

      # 3. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # 使用你项目的 Node.js 版本

      # 4. 安装依赖
      - name: Install dependencies
        run: npm install

      # 5. 构建项目
      - name: Build project
        run: npm run build

      # 6. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # 使用 GitHub token 进行授权
